export { default as About } from "./About.js";
export { default as Home } from "./Home.js";
export { default as Login } from "./Login.js";
export { default as Products } from "./Products.js";
export { default as Review } from "./Review.js";
export { default as Register } from "./Register.js";
export { default as Profile } from "./Profile.js";
export { default as Page404 } from "./Page404.js";
export { default as ProductPage } from "./ProductPage.js";
